/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type RoleAdminChanged = ContractEventLog<{
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
  0: string;
  1: string;
  2: string;
}>;
export type RoleGranted = ContractEventLog<{
  role: string;
  account: string;
  sender: string;
  0: string;
  1: string;
  2: string;
}>;
export type RoleRevoked = ContractEventLog<{
  role: string;
  account: string;
  sender: string;
  0: string;
  1: string;
  2: string;
}>;

export interface ChronoPoolService extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ChronoPoolService;
  clone(): ChronoPoolService;
  methods: {
    DEFAULT_ADMIN_ROLE(): NonPayableTransactionObject<string>;

    POOL_LORD(): NonPayableTransactionObject<string>;

    addChronoPool(
      _ffBasis: number | string | BN,
      _vestPeriod: number | string | BN,
      _apr: number | string | BN
    ): NonPayableTransactionObject<string>;

    chronoPools(arg0: number | string | BN): NonPayableTransactionObject<{
      rateBasis: string;
      chronoVesting: string;
      0: string;
      1: string;
    }>;

    claimAll(): NonPayableTransactionObject<void>;

    claimAndFastForward(
      _pid: number | string | BN
    ): NonPayableTransactionObject<void>;

    claimAndFastForwardAll(): NonPayableTransactionObject<void>;

    claimPool(_pid: number | string | BN): NonPayableTransactionObject<void>;

    claimPoolForTo(
      _for: string,
      _pid: number | string | BN,
      _epoch: number | string | BN
    ): NonPayableTransactionObject<void>;

    czf(): NonPayableTransactionObject<string>;

    deposit(
      _pid: number | string | BN,
      _wad: number | string | BN
    ): NonPayableTransactionObject<void>;

    emergencyFastForward(
      _pid: number | string | BN
    ): NonPayableTransactionObject<void>;

    emergencyFastForwardAll(): NonPayableTransactionObject<void>;

    getAdjustedRateBasis(
      _rateBasis: number | string | BN
    ): NonPayableTransactionObject<string>;

    getChronoPoolAccountInfo(
      _for: string,
      _pid: number | string | BN
    ): NonPayableTransactionObject<{
      totalVesting_: string;
      emissionRate_: string;
      updateEpoch_: string;
      0: string;
      1: string;
      2: string;
    }>;

    getChronoPoolInfo(_pid: number | string | BN): NonPayableTransactionObject<{
      adjustedRateBasis_: string;
      vestPeriod_: string;
      ffBasis_: string;
      poolEmissionRate_: string;
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    getRoleAdmin(role: string | number[]): NonPayableTransactionObject<string>;

    getRoleMember(
      role: string | number[],
      index: number | string | BN
    ): NonPayableTransactionObject<string>;

    getRoleMemberCount(
      role: string | number[]
    ): NonPayableTransactionObject<string>;

    grantRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<void>;

    hasRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<boolean>;

    reinvest(_pid: number | string | BN): NonPayableTransactionObject<void>;

    renounceRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<void>;

    revokeRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<void>;

    setBaseEmissionRate(
      _to: number | string | BN
    ): NonPayableTransactionObject<void>;

    setChronoPool(
      _pid: number | string | BN,
      _ffBasis: number | string | BN,
      _apr: number | string | BN
    ): NonPayableTransactionObject<void>;

    supportsInterface(
      interfaceId: string | number[]
    ): NonPayableTransactionObject<boolean>;
  };
  events: {
    RoleAdminChanged(cb?: Callback<RoleAdminChanged>): EventEmitter;
    RoleAdminChanged(
      options?: EventOptions,
      cb?: Callback<RoleAdminChanged>
    ): EventEmitter;

    RoleGranted(cb?: Callback<RoleGranted>): EventEmitter;
    RoleGranted(
      options?: EventOptions,
      cb?: Callback<RoleGranted>
    ): EventEmitter;

    RoleRevoked(cb?: Callback<RoleRevoked>): EventEmitter;
    RoleRevoked(
      options?: EventOptions,
      cb?: Callback<RoleRevoked>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "RoleAdminChanged", cb: Callback<RoleAdminChanged>): void;
  once(
    event: "RoleAdminChanged",
    options: EventOptions,
    cb: Callback<RoleAdminChanged>
  ): void;

  once(event: "RoleGranted", cb: Callback<RoleGranted>): void;
  once(
    event: "RoleGranted",
    options: EventOptions,
    cb: Callback<RoleGranted>
  ): void;

  once(event: "RoleRevoked", cb: Callback<RoleRevoked>): void;
  once(
    event: "RoleRevoked",
    options: EventOptions,
    cb: Callback<RoleRevoked>
  ): void;
}
