/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type Paused = ContractEventLog<{
  account: string;
  0: string;
}>;
export type RoleAdminChanged = ContractEventLog<{
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
  0: string;
  1: string;
  2: string;
}>;
export type RoleGranted = ContractEventLog<{
  role: string;
  account: string;
  sender: string;
  0: string;
  1: string;
  2: string;
}>;
export type RoleRevoked = ContractEventLog<{
  role: string;
  account: string;
  sender: string;
  0: string;
  1: string;
  2: string;
}>;
export type Unpaused = ContractEventLog<{
  account: string;
  0: string;
}>;

export interface ExoticMaster extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ExoticMaster;
  clone(): ExoticMaster;
  methods: {
    DEFAULT_ADMIN_ROLE(): NonPayableTransactionObject<string>;

    EXOTIC_LORD(): NonPayableTransactionObject<string>;

    addExoticFarm(
      _ffBasis: number | string | BN,
      _vestPeriod: number | string | BN,
      _apr: number | string | BN,
      _lp: string
    ): NonPayableTransactionObject<string>;

    claimAll(): NonPayableTransactionObject<void>;

    claimAndFastForward(
      _pid: number | string | BN
    ): NonPayableTransactionObject<void>;

    claimAndFastForwardAll(): NonPayableTransactionObject<void>;

    claimFarm(_pid: number | string | BN): NonPayableTransactionObject<void>;

    claimFarmForTo(
      _for: string,
      _pid: number | string | BN,
      _epoch: number | string | BN
    ): NonPayableTransactionObject<void>;

    czf(): NonPayableTransactionObject<string>;

    deposit(
      _pid: number | string | BN,
      _wad: number | string | BN
    ): NonPayableTransactionObject<void>;

    emergencyFastForward(
      _pid: number | string | BN
    ): NonPayableTransactionObject<void>;

    emergencyFastForwardAll(): NonPayableTransactionObject<void>;

    exoticFarms(arg0: number | string | BN): NonPayableTransactionObject<{
      rateBasis: string;
      lp: string;
      chronoVesting: string;
      0: string;
      1: string;
      2: string;
    }>;

    fastForwardLockPeriod(): NonPayableTransactionObject<string>;

    getAdjustedRateBasis(
      _rateBasis: number | string | BN,
      _lp: string
    ): NonPayableTransactionObject<string>;

    getCzfPerLPWad(
      oracle: string,
      lp: string
    ): NonPayableTransactionObject<string>;

    getExoticFarmAccountInfo(
      _for: string,
      _pid: number | string | BN
    ): NonPayableTransactionObject<{
      totalVesting_: string;
      emissionRate_: string;
      updateEpoch_: string;
      fastForwardLockToEpoch_: string;
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    getExoticFarmInfo(_pid: number | string | BN): NonPayableTransactionObject<{
      adjustedRateBasis_: string;
      vestPeriod_: string;
      ffBasis_: string;
      poolEmissionRate_: string;
      baseEmissionRate_: string;
      lp_: string;
      czfPerLpWad_: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
      6: string;
    }>;

    getRoleAdmin(role: string | number[]): NonPayableTransactionObject<string>;

    getRoleMember(
      role: string | number[],
      index: number | string | BN
    ): NonPayableTransactionObject<string>;

    getRoleMemberCount(
      role: string | number[]
    ): NonPayableTransactionObject<string>;

    grantRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<void>;

    hasRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<boolean>;

    lpEmissions(arg0: string): NonPayableTransactionObject<{
      baseEmissionRate: string;
      currentEmissionRate: string;
      oracle: string;
      0: string;
      1: string;
      2: string;
    }>;

    paused(): NonPayableTransactionObject<boolean>;

    renounceRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<void>;

    revokeRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<void>;

    setExoticFarmApr(
      _pid: number | string | BN,
      _ffBasis: number | string | BN,
      _apr: number | string | BN
    ): NonPayableTransactionObject<void>;

    setFastForwardLockPeriod(
      _to: number | string | BN
    ): NonPayableTransactionObject<void>;

    setLpBaseEmissionRate(
      _lp: string,
      _to: number | string | BN
    ): NonPayableTransactionObject<void>;

    setPaused(_to: boolean): NonPayableTransactionObject<void>;

    setTreasury(_to: string): NonPayableTransactionObject<void>;

    supportsInterface(
      interfaceId: string | number[]
    ): NonPayableTransactionObject<boolean>;

    treasury(): NonPayableTransactionObject<string>;
  };
  events: {
    Paused(cb?: Callback<Paused>): EventEmitter;
    Paused(options?: EventOptions, cb?: Callback<Paused>): EventEmitter;

    RoleAdminChanged(cb?: Callback<RoleAdminChanged>): EventEmitter;
    RoleAdminChanged(
      options?: EventOptions,
      cb?: Callback<RoleAdminChanged>
    ): EventEmitter;

    RoleGranted(cb?: Callback<RoleGranted>): EventEmitter;
    RoleGranted(
      options?: EventOptions,
      cb?: Callback<RoleGranted>
    ): EventEmitter;

    RoleRevoked(cb?: Callback<RoleRevoked>): EventEmitter;
    RoleRevoked(
      options?: EventOptions,
      cb?: Callback<RoleRevoked>
    ): EventEmitter;

    Unpaused(cb?: Callback<Unpaused>): EventEmitter;
    Unpaused(options?: EventOptions, cb?: Callback<Unpaused>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Paused", cb: Callback<Paused>): void;
  once(event: "Paused", options: EventOptions, cb: Callback<Paused>): void;

  once(event: "RoleAdminChanged", cb: Callback<RoleAdminChanged>): void;
  once(
    event: "RoleAdminChanged",
    options: EventOptions,
    cb: Callback<RoleAdminChanged>
  ): void;

  once(event: "RoleGranted", cb: Callback<RoleGranted>): void;
  once(
    event: "RoleGranted",
    options: EventOptions,
    cb: Callback<RoleGranted>
  ): void;

  once(event: "RoleRevoked", cb: Callback<RoleRevoked>): void;
  once(
    event: "RoleRevoked",
    options: EventOptions,
    cb: Callback<RoleRevoked>
  ): void;

  once(event: "Unpaused", cb: Callback<Unpaused>): void;
  once(event: "Unpaused", options: EventOptions, cb: Callback<Unpaused>): void;
}
